name: Test and Deploy

# Run this workflow whenever something new is pushed.
on: 
  push:
    branches: main

jobs:
  testing:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install Dependencies
        run: pip install -U -r requirements.txt
      - name: Run tests
        run: pytest
  deployment:
    runs-on: ubuntu-20.04
    needs: testing
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Deploy App to DigitalOcean
        uses: appleboy/scp-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.DO_KEY }}
          source: "app/*,run.py,requirements.txt,scripts/update.sh"
          target: "/home/cd-example"
  remote_setup:
    runs-on: ubuntu-20.04
    needs: deployment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Update Remote Python Modules
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DO_KEY }}
          port: ${{ secrets.PORT }}
          script: sh scripts/update.sh

        

